// Shared allowlist for the internal analytics/funnel tracking system.
// Used by both the client tracker (lib/analytics/track.js) and the
// server write route (app/api/track/route.js) so they can never drift.

export const ANALYTICS_EVENTS = [
  "analytics_consent_granted",
  "landing_page_view",
  "hero_cta_clicked",
  "signup_started",
  "account_created",
  "onboarding_started",
  "onboarding_step_completed",
  "position_calculated",
  "preview_start_requested",
  "preview_started",
  "preview_reminder_sent",
  "preview_reminder_opened",
  "balance_updated_during_preview",
  "position_recalculated_during_preview",
  "preview_expired",
  "upgrade_offer_viewed",
  "upgrade_checkout_started",
  "subscription_started",
  "payday_added",
  "bill_input_started",
  "bill_reviewed",
  "bill_added",
  "forecast_viewed",
  "paywall_viewed",
  "checkout_started",
  "checkout_completed",
  "subscription_created",
  "subscription_cancelled",
  "login",
  "logout",
  "ad_landing_view",
  "try_now_clicked",
  "first_clear_result_viewed",
  "trial_offer_viewed",
  "trial_checkout_started",
  "trial_started",
  "trial_cancelled",
  "first_invoice_paid",
  "renewal_invoice_paid",
  "invoice_payment_failed",
  "lead_magnet_popup_eligible",
  "lead_magnet_popup_viewed",
  "lead_magnet_popup_dismissed",
  "lead_magnet_form_started",
  "lead_magnet_submitted",
  "lead_magnet_marketing_opt_in",
  "lead_magnet_pdf_downloaded",
  "lead_magnet_sheet_downloaded",
  "lead_magnet_google_copy_clicked",
  "lead_magnet_to_preview_clicked",
  "lead_magnet_preview_started",
  "notification_decision",
  "notification_delivery",
  "notification_activity",
];

// The subsequence of ANALYTICS_EVENTS that represents linear progress
// toward payment. Used to render the funnel section in /admin/analytics.
export const FUNNEL_STAGES = [
  "ad_landing_view",
  "try_now_clicked",
  "onboarding_started",
  "first_clear_result_viewed",
  "trial_offer_viewed",
  "trial_checkout_started",
  "trial_started",
  "trial_cancelled",
  "first_invoice_paid",
  "renewal_invoice_paid",
  "invoice_payment_failed",
];

// Events that represent forward progress and are worth recording as the
// customer's current drop-off stage on their customers/{uid} record.
export const DROP_OFF_STAGE_EVENTS = new Set([
  "onboarding_started",
  "bill_added",
  "forecast_viewed",
  "paywall_viewed",
  "checkout_started",
]);
